[PHP]
display_errors = On
error_reporting = E_ALL
max_execution_time = 30
max_input_time = 60
memory_limit = 256M
post_max_size = 100M
upload_max_filesize = 100M

[Date]
date.timezone = America/Mexico_City

[Session]
session.gc_maxlifetime = 1440