[PHP]
display_errors = On
error_reporting = E_ALL
max_execution_time = 30
max_input_time = 60
memory_limit = 256M
post_max_size = 100M
upload_max_filesize = 100M

; Charset UTF-8 para todas las salidas HTML
default_charset = "utf-8"

; Locales en español para fechas y mensajes
[Date]
date.timezone = America/Mexico_City

[Locale]
intl.default_locale = es_MX.UTF-8